project:
  type: website

website:
  site-url: "https://bkaradenes25.github.io/"
  title: "Brendan Karadenes"
  navbar:
    Right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: courses.qmd
        text: Courses
      - href: projects.qmd
        text: Projects
      - text: Contact
        menu:
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/brendan-karadenes-847962252/
            target: _blank
          - icon: envelope
            text: Email
            href: mailto:bekara21@stlawu.edu
          - icon: github
            text: GitHub
            href: https://github.com/bkaradenes25
            target: _blank

format:
  html:
    page-layout: full
    sidebar: false
    theme: cosmo
    css: styles.css
    toc: true



