---
title: "Courses"
---

Here are some details about the relevant coursework that I have completed at St. Lawrence University.

::: {.callout-note collapse="true" title="Applied Regression Analysis" appearance="simple"}
A mid-level statistics class focused on applying data using R. Topics include simple and multiple linear regression, model diagnostics and testing, residual analysis, transformations, indicator variables, variable selection techniques, logistic regression, and analysis of variance. 
:::

::: {.callout-note collapse="true" title="Intro to Data Science" appearance="simple"}
The course focused on applying data science and statistical methods using R. Topics included data manipulation and visualization, programming, string manipulation, and modern data sources (such as web and databases). This course taught the building blocks of larger scale data science projects.
:::

::: {.callout-note collapse="true" title="Data Structures" appearance="simple"}
The course used strategies in Java to organize, process, and retrieve data. Topics included arrays, lists, stacks, queues, maps, trees, and algorithm analysis. 
:::

::: {.callout-note collapse="true" title="Data Visualization" appearance="simple"}
An upper level statistics class focused on visualizing data using R. Topics include mapping data, linear regression, logistic regression, interactivity, and building a shiny app. The course includes an introduction to computer analysis of data with a statistical computing package. There was a heavy focus on ethically communicating and presenting data.
:::

::: {.callout-note collapse="true" title="Database Systems" appearance="simple"}
An upper level computer science class focused on using SQL and Python. A look at how data is logically organized, physically stored on a digital device, and queried. Focuses primarily on relational database systems and structured queries. Other topics include non-relational data models, privacy, security, performance, and reliability.
:::

::: {.callout-note collapse="true" title="Time Series Analysis" appearance="simple"}
An upper level statistics class. Statistical methods for analyzing data that vary over time are investigated. Topics may include forecasting systems, regression methods, moving averages, exponential smoothing, seasonal data, analysis of residuals, prediction intervals and Box-Jenkins models. Application to real data, particularly economic data, is emphasized along with the mathematical theory underlying the various models and techniques.
:::

::: {.callout-note collapse="true" title="Statistical and Machine Learning" appearance="simple"}
Introduces techniques for developing advanced models from datasets, for the purposes of better understanding the data and making predictions about future data. Techniques include linear and regularized regression, nearest neighbor classification, support vector machines, decision tree ensembles, and neural networks. Examines real-world applications, both successes and failures, the latter of which often involve data with embedded biases. Students will develop both technical and ethical competence in using some of the most powerful computational tools in data science.
:::

